version: '3.3'
services:
  web:
    build:
      args:
        - conf=./web/web-nginx.development.conf
    depends_on:
      - chill
  chill:
    command: run
    volumes:
      # /usr/run/root is a volume and is shared with web (nginx)

      # bind to allow ease of adding documents and queries without rebuilding
      - type: bind
        source: ./documents
        target: /usr/run/documents
        read_only: true
      - type: bind
        source: ./queries
        target: /usr/run/queries
        read_only: true

      # media files are compiled from another container
      - type: volume
        source: media
        target: /usr/run/media

      # dist files are compiled from another container
      - type: volume
        source: dist
        target: /usr/run/dist

      # SQLite database can be edited via local gui apps (use with care)
      - type: bind
        source: ./db
        target: /usr/run/db
      - type: bind
        source: ./db.dump.sql
        target: /usr/run/db.dump.sql
  api:
    volumes:
      - type: bind
        source: ./site.cfg
        target: /code/site.cfg
        read_only: true
      - type: bind
        source: ./package.json
        target: /code/package.json
        read_only: true
      - type: bind
        source: ./api/src
        target: /code/src

volumes:
  dist:
  media:
